import {
  AVOID,
  FIELD_REQUIREMENTS,
  INTERNAL_PROCESS_DAILY,
  INTERNAL_PROCESS_EXPANSIVE,
  INTRO_DAILY,
  INTRO_EXPANSIVE,
  NOVELTY,
  OUTPUT_FORMAT,
  OUTPUT_FORMAT_EXPANSIVE,
  PURPOSE_DAILY,
  PURPOSE_EXPANSIVE,
  QUALITY_CHECK_DAILY,
  STYLE_EXEMPLARS_EXPANSIVE,
  TONE,
  WHAT_GOOD_QUESTIONS_DO,
} from "./chunks";

export const DAILY_GENERATOR_PROMPT = [
  INTRO_DAILY,
  PURPOSE_DAILY,
  TONE,
  AVOID,
  WHAT_GOOD_QUESTIONS_DO,
  NOVELTY,
  INTERNAL_PROCESS_DAILY,
  QUALITY_CHECK_DAILY,
  OUTPUT_FORMAT,
  FIELD_REQUIREMENTS,
].join("\n\n");

export const EXPANSIVE_GENERATOR_PROMPT = [
  INTRO_EXPANSIVE,
  PURPOSE_EXPANSIVE,
  TONE,
  AVOID,
  WHAT_GOOD_QUESTIONS_DO,
  NOVELTY,
  STYLE_EXEMPLARS_EXPANSIVE,
  INTERNAL_PROCESS_EXPANSIVE,
  OUTPUT_FORMAT_EXPANSIVE,
  FIELD_REQUIREMENTS,
].join("\n\n");
